// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: mono knip generate
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    entry: ["src/index.ts"],
    project: ["src/**/*.ts"],
}, {
    "ignoreDependencies": [
        "@adddog/monorepo-consistency"
    ],
    "ignoreBinaries": [
        "knip",
        "tsx"
    ],
    "entry": [
        "src/index.ts",
        "src/setup-vitest.ts",
        "src/app.config.ts",
        "src/test.config.ts"
    ]
});
