// Generated by @adddog/monorepo-consistency
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "@adddog/monorepo-consistency";

export default defineKnipConfig({
    entry: ["src/index.ts"],
    project: ["src/**/*.ts"],
    ignoreBinaries: ["knip", "tsx"],
    ignoreDependencies: [
        "@rad/config",
        "ts-toolbelt",
        // Optional vite plugins exported for consumers
        "@testing-library/jest-dom",
        "@vitejs/plugin-vue",
        "urlpattern-polyfill",
        "vite-plugin-svgr",
        "vitest-canvas-mock",
    ],
    ignore: [
        // Vitest setup - referenced from vitest configs
        "src/setup-vitest.ts",
        "src/types.ts",
    ],
});
